# Generated by Django 3.2.7 on 2023-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('cid', models.CharField(max_length=150)),
                ('apid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('cmpid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('p_age', models.CharField(max_length=150)),
                ('p_email', models.CharField(max_length=150)),
                ('p_phone', models.CharField(max_length=150)),
                ('p_password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='pcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('princy', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='principals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='prodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('p_age', models.CharField(max_length=150)),
                ('p_email', models.CharField(max_length=150)),
                ('p_phone', models.CharField(max_length=150)),
                ('p_password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='staffcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('princy', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='stdcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('hod', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=150)),
                ('st_email', models.CharField(max_length=150)),
                ('st_department', models.CharField(max_length=150)),
                ('st_semester', models.CharField(max_length=150)),
                ('st_phone', models.CharField(max_length=150)),
                ('st_password', models.CharField(max_length=150)),
                ('st_fathername', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=150)),
                ('t_email', models.CharField(max_length=150)),
                ('t_department', models.CharField(max_length=150)),
                ('t_semester', models.CharField(max_length=150)),
                ('t_password', models.CharField(max_length=150)),
            ],
        ),
    ]
