# Generated by Django 3.2.17 on 2023-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_attendance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_id', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
