# Generated by Django 3.2.7 on 2026-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0002_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendance',
            name='time',
            # Use a valid time default for existing rows
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
    ]
