# Generated by Django 3.2.7 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0003_student_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='time',
            field=models.TimeField(),
        ),
    ]
