# Generated by Django 3.2.7 on 2026-02-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0004_add_slot_field'),
        ('studentgrievence', '0005_chatmessage'),
    ]

    operations = [
    ]
