# Generated by Django 3.2.7 on 2026-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0006_merge_0004_add_slot_field_0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='parent_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
