# Generated by Django 3.2.7 on 2026-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0007_students_parent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=150)),
                ('slot', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
