# Generated by Django 3.2.7 on 2026-02-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgrievence', '0008_teacher_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher_attendance',
        ),
    ]
